import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
import {ambienteFila} from '../backend/tests/fixtures/fila.mjs';
let e,browser;
try{
 e=await ambienteFila();await mkdir('artifacts/deploy',{recursive:true});browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],requests=[];page.on('pageerror',()=>errors.push('ERRO_JS'));page.on('request',r=>requests.push(r.url()));
 const login=async role=>{await page.fill('#email',role+'@fila.local');await page.fill('#password',e.senha);await page.click('#login-submit');await page.locator('#app-view').waitFor({state:'visible'});await page.click('[data-page="queue"]');await page.locator('.queue-setup,.queue-summary').first().waitFor();};
 const post=async fn=>{const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/fila')&&r.request().method()==='POST');await fn();assert.equal((await response).status(),200);};
 await page.goto(e.base);await login('admin');await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/deploy/fila-abertura-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 for(const c of ['10','20','30']){await page.getByLabel('Vendedor presente',{exact:true}).selectOption(c);await page.getByRole('button',{name:'Adicionar presente',exact:true}).click();}
 await post(()=>page.getByRole('button',{name:'Abrir jornada',exact:true}).click());await page.getByText('Na vez: Ana Exemplo',{exact:true}).waitFor();
 const ana=page.locator('[data-vendedor="10"]'),bruno=page.locator('[data-vendedor="20"]');
 await post(()=>ana.getByRole('button',{name:'Abordar próximo cliente',exact:true}).click());await ana.getByRole('button',{name:'Encerrar sem iniciar',exact:true}).click();await page.fill('#queue-reason','Cliente só olhando');await post(()=>page.locator('#queue-action-form button[type="submit"]').click());await page.getByText('Na vez: Ana Exemplo',{exact:true}).waitFor();
 await ana.getByRole('button',{name:'Pausar',exact:true}).click();await page.fill('#queue-reason','Almoço');await post(()=>page.locator('#queue-action-form button[type="submit"]').click());await ana.getByRole('button',{name:'Retornar da pausa',exact:true}).waitFor();await post(()=>ana.getByRole('button',{name:'Retornar da pausa',exact:true}).click());await page.getByText('Na vez: Bruno Exemplo',{exact:true}).waitFor();
 await post(()=>bruno.getByRole('button',{name:'Abordar próximo cliente',exact:true}).click());await post(()=>bruno.getByRole('button',{name:'Iniciar atendimento',exact:true}).click());await bruno.getByRole('button',{name:'Concluir sem venda',exact:true}).click();await page.fill('#queue-reason','Tamanho indisponível');await post(()=>page.locator('#queue-action-form button[type="submit"]').click());await page.getByText('Na vez: Carla Exemplo',{exact:true}).waitFor();
 await ana.getByRole('button',{name:'Cliente reservado',exact:true}).click();await page.fill('#queue-reason','Retorno ao vendedor');await post(()=>page.locator('#queue-action-form button[type="submit"]').click());await post(()=>ana.getByRole('button',{name:'Iniciar atendimento',exact:true}).click());await ana.getByRole('button',{name:'Concluir com venda',exact:true}).click();await page.getByText('O resultado será informado por você.',{exact:false}).waitFor();await post(()=>page.locator('#queue-action-form button[type="submit"]').click());await page.getByText('Na vez: Carla Exemplo',{exact:true}).waitFor();
 await page.locator('#queue-filters button:not([disabled])').waitFor();await page.locator('#queue-filters button').click();await page.getByText('Na vez: Carla Exemplo',{exact:true}).waitFor();
 await page.screenshot({path:'artifacts/deploy/fila-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/deploy/fila-mobile.png',fullPage:true});
 // A recarga preserva o estado no banco e o vendedor só recebe seus controles.
 await page.click('#logout');await login('vendas');await ana.getByRole('button',{name:'Cliente reservado',exact:true}).waitFor();assert.equal(await bruno.getByRole('button').count(),0);assert.equal(await page.getByRole('button',{name:'Fechar jornada',exact:true}).count(),0);
 await ana.getByRole('button',{name:'Cliente reservado',exact:true}).click();await page.fill('#queue-reason','Cliente retornou');await post(()=>page.locator('#queue-action-form button[type="submit"]').click());await ana.getByRole('button',{name:'Iniciar atendimento',exact:true}).waitFor();await page.reload();await login('vendas');await ana.getByRole('button',{name:'Iniciar atendimento',exact:true}).waitFor();assert.equal(await bruno.getByRole('button').count(),0);
 await page.screenshot({path:'artifacts/deploy/fila-vendedor-mobile.png',fullPage:true});assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith(e.base)));await page.click('#logout');
 await writeFile('docs/validacao-fila-ui.json',JSON.stringify({verificadoEm:new Date().toISOString(),ambiente:'schemas temporários com dados sintéticos',abertura:true,naoIniciadoPreservaVez:true,pausaRetornaFinal:true,semVendaVaiFinal:true,reservadoPreservaVez:true,resultadoInformado:true,vendedorSomentePropriosControles:true,persistenciaAposRecarga:true,desktopMobile:true,mobileSemOverflow:true,semERP:true,errors},null,2)+'\n');console.log('Fila validada: jornada, vez, pausa, reservado e acesso de vendedor em desktop/celular.');
}finally{await browser?.close();await e?.close();}
